#!/usr/bin/env bash

session=$(find ~ ~/Documents/Repos -mindepth 1 -maxdepth 3 -type d | fzf)

session_name=$(basename "$session" | tr . _) # replace periods with underscore

if ! tmux has-session -t "$session_name"; then
  tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"
