#!/usr/local/bin/bash

# current_session_name=$(tmux display-message '#S' | sed -E 's/:.*$//')

session_name=$(tmux list-sessions | sed -E 's/:.*$//' | grep -v "^$(tmux display-message -p '#S')\$" | fzf --reverse)

if [[ -n $session_name ]]; then
  tmux switch-client -t "$session_name"
fi
