#!/usr/local/bin/bash

declare -A repos
repos[ad-demo-platform]=demo
repos[ad-composer]=composer
repos[ad-composer-react]=composer
repos[ad-kailtra]=kailtra
repos[ad-krab]=ad-krab
repos[ad-snippet-service]=snippet-service
repos[ad-tag]=ad-tag
repos[ControlPanel]=marketplace
repos[deal-manager]=deal-manager
repos[pegasus]=pegasus
repos[video-tag-builder]=video-tag-builder

update_development_json () {
  original_host=$1.krg.io
  extra=$2
  new_host=$1-$extra.krg.io

  development_json=$(find $(pwd) -name  "development.json")

  if [ -e "$development_json" ] && grep -q "$original_host" $development_json; then
    sed -i '' "s/$original_host/$new_host/g" $development_json
    echo "Updated development.json"
  fi
}

update_docker_compose_yml () {
  original_host=$1.krg.io
  extra=$2
  new_host=$1-$extra.krg.io

  docker_compose_yml=$(find $(pwd) -name "docker-compose.yml")

  if grep -q "$original_host" $docker_compose_yml; then
    # Update container name
    sed -i '' "s/\(container_name: \)\(.*\)$/\1\2-$extra/" $docker_compose_yml
    # Update host
    sed -i '' "s/$original_host/$new_host/g" $docker_compose_yml
    # Comment out specific ports
    sed -i '' "s/\( *\)\(- \"[0-9]*:[0-9]*\"\)/\1# \2/g" $docker_compose_yml
    # Update Traefik services and routers
    sed -i '' "s/\(traefik\.http\.[^\.]*\.\)\([^\.]*\)\(.*\)/\1\2-$extra\3/g" $docker_compose_yml
    echo "Updated docker-compose.yml"
  fi
}

# Composer UI
update_config_ts () {
  config_ts=$(find . -name "config.ts" ! -path "./node_modules/*")
  subdomain="composer"

  if [ "$1" != "" ]; then
    subdomain="composer-$1"
  fi

  if [ -e "$config_ts" ] && grep -q "API_URL: ''," $config_ts; then
    sed -i '' "s/API_URL: '',/API_URL: 'https:\/\/$subdomain.krg.io',/g" $config_ts
    echo "Updated config.ts"
  fi
}

# Composer API
update_app_js () {
  app_js=$(find $(pwd) -name "app.js")

  if [ -e "$app_js" ] && grep -q "const app = express();" $app_js; then
    sed -i '' "s/const app = express();/const cors = require('cors');\nconst app = express();\napp.use(cors());\n/g" $app_js
    echo "Updated app.js"
  fi
}

echo -n "Select repo:"
current_repo=$(printf '%s\n' "${!repos[@]}" | fzf)
echo $current_repo

echo -n "Enter unique name to append: "
read extra_name

update_docker_compose_yml ${repos[$current_repo]} $extra_name
update_development_json ${repos[$current_repo]} $extra_name

if [[ "$current_repo" =~ ad-composer-react ]]; then
  echo -e "Change Composer API?\nPress Return or Space for no change.\nPress any other key to change the domain)."
  while true; do
    read -rsn1 input
    if [ "$input" = "" ]; then
      echo -e "composer.krg.io"
      update_config_ts
      break
    else
      echo -e "composer-$extra_name.krg.io"
      update_config_ts $extra_name
      break
    fi
  done
fi

if [[ "$current_repo" =~ ad-composer ]]; then
  update_app_js
fi

echo "Done."
