return {
  -- none-ls.nvim
  -- {
  --   "nvimtools/none-ls.nvim",
  --   opts = function(_, opts)
  --     local nls = require("null-ls")
  --     opts.sources = vim.list_extend(opts.sources or {}, {
  --       nls.builtins.formatting.fish_indent,
  --       nls.builtins.formatting.gofumpt,
  --       nls.builtins.formatting.goimports,
  --       nls.builtins.formatting.prettierd,
  --       nls.builtins.formatters.shfmt,
  --       nls.builtins.formatters.sql_formatter,
  --       nls.builtins.formatting.stylua,
  --
  --       -- Linters
  --       nls.builtins.code_actions.eslint,
  --       nls.builtins.diagnostics.golangcit_lint,
  --       nls.builtins.diagnostics.shellcheck,
  --       nls.builtins.diagnostics.sqlfluff.with({
  --         extra_args = { "--dialect", "postgres" },
  --       }),
  --     })
  --     return opts
  --   end,
  -- },
}
