return {
  --   {
  --     "pmizio/typescript-tools.nvim",
  --     dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
  --     opts = {
  --       settings = {
  --         tsserver_file_preferences = {
  --           disableSuggestions = false,
  --           includeCompletionsForModuleExports = true,
  --           includeAutomaticOptionalChainCompletions = true,
  --           includeInlayParameterNameHints = "all",
  --           includeInlayVariableTypeHints = true,
  --           quotePreference = "auto",
  --         },
  --         tsserver_format_options = {
  --           allowIncompleteCompletions = false,
  --           allowRenameOfImportPath = true,
  --           insertSpaceAfterCommaDelimiter = true,
  --           insertSpaceAfterSemicolonInForStatements = true,
  --           semicolons = true,
  --         },
  --       },
  --     },
  --   },
}
